/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-11-25 17:07:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Topo.jsp", Long.valueOf(1448471242142L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1440509386000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Ranktoon</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/bootstrap.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      out.write("<img alt=\"Topo\" src=\"IMG/Topo.png\" class=\"img-thumbnail\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<p>                                                                    </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"busca\" placeholder=\"Busca\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Buscar\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"http://alsolo.com.br/img/projetos/538264d54e87e.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Bar do zé\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Bar do zé</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Endereço: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Telefone: blablabla</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Avaliação: tananan</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Mais\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformações</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
